@startuml model

  class User<<Пользователь>>{
    # id
    # code
    + name
  }

  class Chat <<Чат>>{
    # id
    # uid
    # code
    + name
    + begDate
    + endDate
  }

  class ChatMemberRole <<Роль участника>>{
    # id
    + code
    + name
  }

  ChatMember .. "1" ChatMemberRole

  class ChatMember<<Участник чата>> {
    # id
    + user: User
    + chat: Chat
    + role: ChatMemberRole <<Роль>>
    + begDate: DateTime
    + endDate: DateTime
  }

  User "1" *-- "M" ChatMember : является >
  Chat "1" *-- "M" ChatMember : содержит >


  class Message <<Сообщение>>{
    # id
    + date
    + author: User
    + text
    + attachments[]
    + chatMember
  }

  class Attachment <<Вложение>>{
    # id
    + date
    + name
    + contentType
    + content
  }

  Message "1" *-- "M" Attachment : содержит >


  Chat "1" *-- "M" Message : содержит >



@enduml
